# Change these first
owner: Baronhez # Your GitHub organization or username, where this repository lives
repo: Uptimer # The name of this repository

sites:
  - name: WebPage CV
    url: https://jonthan.xyz
  - name: Server Dashboard
    url: https://server.jonthan.xyz
  - name: Speedtest on my server
    url: https://speedtest.jonthan.xyz
  - name: Bookmark Manager on my server
    url: https://linkding.jonthan.xyz
  - name: Filebrowser on my server
    url: https://filebrowser.jonthan.xyz
  - name: Actual on my server
    url: https://actual.jonthan.xyz
  - name: Traefik Dashboard on my server
    url: https://traefik.jonthan.xyz
    

assignees: # Users to assign downtime issues (optional)
  - Baronhez

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Uptimer
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Baronhez Status
  introTitle: "This page allows me to check if my pages are fully operational :)"
  introMessage: The code used for this page is from this [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: https://baronhez.github.io/Uptimer/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
